# contract_review_app/config.py
# Canonical clause keywords (ALL LOWERCASE). Kept broad enough for robust recall.
# Matching/normalization is handled downstream by intake/patterns.py.

import os


FEATURE_COMPANIES_HOUSE = (os.getenv("FEATURE_COMPANIES_HOUSE", "").strip())
CH_API_KEY = (os.getenv("CH_API_KEY") or os.getenv("COMPANIES_HOUSE_API_KEY", "")).strip()
CH_ENABLED = FEATURE_COMPANIES_HOUSE in {"1", "true", "True"} and CH_API_KEY != ""


CLAUSE_KEYWORDS = {
    # Core
    "definitions": [
        "definition",
        "definitions",
        "shall mean",
        "means",
        "interpretation",
    ],
    "term": [
        "term",
        "duration",
        "commencement",
        "effective date",
        "expiry",
        "expiration",
        "renewal",
        "extend",
        "extension",
    ],
    "termination": [
        "terminate",
        "termination",
        "material breach",
        "breach",
        "notice",
        "insolvency",
        "bankruptcy",
        "failure to perform",
        "non-performance",
        "suspension",
        "for convenience",
        "for cause",
        "cure period",
    ],
    "payment": [
        "payment",
        "payments",
        "fees",
        "charges",
        "price",
        "cost",
        "invoice",
        "due date",
        "payment terms",
        "set-off",
        "withhold",
        "interest on late payment",
    ],
    "deliverables_acceptance": [
        "deliverables",
        "delivery",
        "acceptance",
        "acceptance criteria",
        "inspection",
        "acceptance testing",
        "rejection",
        "nonconforming",
        "delivery schedule",
    ],
    "governing_law": [
        "governing law",
        "this agreement shall be governed by",
        "laws of",
        "subject to the laws of",
    ],
    "jurisdiction": [
        "jurisdiction",
        "exclusive jurisdiction",
        "non-exclusive jurisdiction",
        "submit to the courts of",
        "courts of",
    ],
    "dispute_resolution": [
        "dispute",
        "dispute resolution",
        "arbitration",
        "mediate",
        "mediation",
        "arbitral",
        "seat of arbitration",
        "lcia",
        "icc",
    ],
    "confidentiality": [
        "confidential",
        "confidentiality",
        "confidential information",
        "non-disclosure",
        "nda",
        "keep confidential",
        "proprietary information",
    ],
    "data_protection": [
        "data protection",
        "personal data",
        "gdpr",
        "uk gdpr",
        "data controller",
        "processor",
        "processing",
        "dpa",
        "data subject",
        "information security",
    ],
    "limitation_of_liability": [
        "limitation of liability",
        "liability shall not exceed",
        "maximum liability",
        "aggregate liability",
        "cap on liability",
        "indirect",
        "consequential",
        "special damages",
        "loss of profits",
        "exclusion of liability",
        "carve-out",
    ],
    "indemnity": [
        "indemnify",
        "indemnification",
        "hold harmless",
        "defend",
        "liabilities",
        "losses",
        "claims",
        "expenses",
        "damages",
        "third party claim",
    ],
    "force_majeure": [
        "force majeure",
        "acts of god",
        "beyond reasonable control",
        "war",
        "riot",
        "strike",
        "lockout",
        "epidemic",
        "pandemic",
        "natural disaster",
        "government action",
        "delay",
        "interruption",
    ],
    "warranties": [
        "warranty",
        "warranties",
        "represents and warrants",
        "representation",
        "merchantability",
        "fitness for a particular purpose",
        "non-infringement",
    ],
    "intellectual_property": [
        "intellectual property",
        "ip",
        "ownership",
        "background ip",
        "foreground ip",
        "license",
        "licence",
        "licensor",
        "licensee",
        "retain all rights",
        "assignment of rights",
    ],
    "change_control": [
        "change control",
        "variation",
        "amend",
        "amendment",
        "modify",
        "modification",
        "change request",
        "change order",
    ],
    "assignment_novation": [
        "assignment",
        "assign",
        "novate",
        "novation",
        "transfer of rights",
        "subrogation",
    ],
    "subcontracting": [
        "subcontract",
        "subcontracting",
        "subcontractor",
        "engage third parties",
    ],
    "notices": [
        "notice",
        "notices",
        "written notice",
        "served",
        "service of notice",
        "address for service",
        "email notice",
        "registered post",
        "deemed receipt",
    ],
    "entire_agreement": [
        "entire agreement",
        "whole agreement",
        "entire understanding",
        "supersedes",
        "previous agreements",
        "this agreement constitutes",
        "merger clause",
        "integration",
    ],
    # Useful boilerplate catches
    "severability": [
        "severable",
        "severability",
        "invalid or unenforceable",
        "remaining provisions",
        "continue in full force",
    ],
    "waiver": ["waiver", "no waiver", "failure to enforce", "no implied waiver"],
    "counterparts": [
        "counterparts",
        "executed in counterparts",
        "facsimile",
        "electronic signature",
    ],
}

# Common alternative headings → canonical keys (ALL LOWERCASE)
ALIASES = {
    # Headings & common pairs
    "definitions and interpretation": "definitions",
    "interpretation": "definitions",
    "duration": "term",
    "term and termination": "termination",
    "termination and suspension": "termination",
    "payment terms": "payment",
    "fees and payment": "payment",
    "deliverables and acceptance": "deliverables_acceptance",
    "delivery and acceptance": "deliverables_acceptance",
    "governing law and jurisdiction": "governing_law",
    "jurisdiction and governing law": "governing_law",
    "choice of law": "governing_law",
    "venue": "jurisdiction",
    "dispute resolution and arbitration": "dispute_resolution",
    "confidential information": "confidentiality",
    "non-disclosure agreement": "confidentiality",
    "nda": "confidentiality",
    "data privacy": "data_protection",
    "data protection and privacy": "data_protection",
    "liability": "limitation_of_liability",
    "limitation": "limitation_of_liability",
    "cap on liability": "limitation_of_liability",
    "indemnities": "indemnity",
    "force-majeure": "force_majeure",
    "warranty": "warranties",
    "ip": "intellectual_property",
    "intellectual property rights": "intellectual_property",
    "ipr": "intellectual_property",
    "variation": "change_control",
    "change order": "change_control",
    "assignment": "assignment_novation",
    "novations": "assignment_novation",
    "sub-contracting": "subcontracting",
    "service of notices": "notices",
    "notices and communications": "notices",
    "entire agreement and variation": "entire_agreement",
    "merger": "entire_agreement",
    "integration": "entire_agreement",
    "severability and waiver": "severability",
}
