vector:
  backend: "inmemory"
  embedding_dim: 128
  embedding_version: "emb-dev-1"
  cache_dir: ".cache/retrieval"
fusion:
  method: "rrf"
  weights:
    vector: 0.6
    bm25: 0.4
  rrf_k: 60
bm25:
  top: 10
