"""Zone metadata and curation hints for the coverage map."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, FrozenSet, Mapping, Tuple


@dataclass(frozen=True)
class ZoneSeed:
    """Declarative seed configuration for a coverage zone."""

    zone_id: str
    zone_name: str
    description: str
    label_hints: Tuple[str, ...]
    rule_hints: Tuple[str, ...]
    entity_selectors: Mapping[str, bool]
    weight: float = 1.0
    required: bool = False
    high_importance: bool = False


ZONE_SEED_DATA: Tuple[ZoneSeed, ...] = (
    ZoneSeed(
        zone_id="payment",
        zone_name="Payment & Invoicing",
        description=(
            "Payment obligations, invoicing mechanics, withholding and set-off "
            "controls."
        ),
        label_hints=(
            "payment_terms",
            "payment_security",
            "late_payment_interest",
            "service_credits",
            "set_off",
            "taxes_vat",
            "open_book_pricing",
            "rate_card",
        ),
        rule_hints=(
            "payment",
            "invoice",
            "billing",
            "withhold",
            "set-off",
            "credit",
            "vat",
        ),
        entity_selectors={
            "amounts": True,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
        weight=1.0,
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="term",
        zone_name="Term & Renewal",
        description="Contract duration, renewal cycles and suspension windows.",
        label_hints=("term", "renewal_auto", "suspension", "usage_limits", "survival"),
        rule_hints=("term", "renewal", "duration", "expiry", "extension"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="termination",
        zone_name="Termination Rights",
        description="Termination for breach, convenience, insolvency and related cure steps.",
        label_hints=(
            "termination_breach",
            "termination_convenience",
            "termination_insolvency",
            "termination_assistance",
            "termination_change_of_control",
        ),
        rule_hints=("terminate", "termination", "cure", "for cause", "for convenience"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="notices",
        zone_name="Notices",
        description="Service of notices, delivery methods and notice periods.",
        label_hints=(
            "notices",
            "foi",
            "lead_times",
            "escalation",
            "service_levels_sla",
        ),
        rule_hints=("notice", "notification", "address", "served", "service"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="governing_law",
        zone_name="Governing Law",
        description="Choice of law, statutory references and conflict rules.",
        label_hints=(
            "governing_law",
            "severance",
            "waiver",
            "entire_agreement",
            "third_party_rights",
            "remedies",
        ),
        rule_hints=("law", "governed", "statute", "jurisdiction", "governing"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": True,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="jurisdiction",
        zone_name="Jurisdiction & Forum",
        description="Courts, venues and escalation forums for disputes.",
        label_hints=(
            "jurisdiction",
            "dispute_resolution",
            "arbitration",
            "mediation",
            "escalation",
        ),
        rule_hints=("jurisdiction", "forum", "court", "venue", "seat", "arbitration"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": True,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="dispute_resolution",
        zone_name="Dispute Resolution",
        description="Mediation, arbitration and escalation procedures.",
        label_hints=(
            "dispute_resolution",
            "arbitration",
            "mediation",
            "escalation",
            "foi",
        ),
        rule_hints=("dispute", "escalation", "arbitration", "mediation", "adr"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="liability_cap",
        zone_name="Liability & Caps",
        description="Limitation of liability, carve outs and capped exposure.",
        label_hints=(
            "limitation_of_liability",
            "liability_cap_amount",
            "liability_carveouts",
            "indirect_consequential_exclusion",
            "liquidated_damages",
            "deductibles_limits",
        ),
        rule_hints=(
            "liability",
            "cap",
            "carve",
            "indirect",
            "consequential",
            "liquidated",
        ),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="indemnity",
        zone_name="Indemnities",
        description="Scope of indemnities, defence obligations and exclusions.",
        label_hints=(
            "indemnity_general",
            "ip_indemnity",
            "dp_indemnity",
            "waiver_of_subrogation",
            "insurance_requirements",
        ),
        rule_hints=(
            "indemn",
            "hold harmless",
            "defence",
            "defense",
            "third party claim",
        ),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="confidentiality",
        zone_name="Confidentiality & Publicity",
        description="Confidential information handling, permitted disclosures and publicity.",
        label_hints=(
            "confidentiality",
            "nhs_patient_confidentiality",
            "permitted_disclosures",
            "return_or_destruction",
            "announcements_publicity",
            "transparency_publication",
        ),
        rule_hints=(
            "confidential",
            "nda",
            "non-disclosure",
            "publicity",
            "announcement",
            "disclosure",
        ),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="ip",
        zone_name="Intellectual Property",
        description="IP ownership, licensing, infringement indemnities and tooling.",
        label_hints=(
            "ip_ownership",
            "license_grant",
            "ip_indemnity",
            "open_source",
            "tooling",
            "title_retention_rot",
        ),
        rule_hints=(
            "intellectual",
            "ip",
            "license",
            "licence",
            "ownership",
            "infringe",
            "tooling",
        ),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="data_protection",
        zone_name="Data Protection",
        description="GDPR roles, processing instructions, breach notification and sub-processing.",
        label_hints=(
            "dp_general",
            "dp_roles",
            "dp_breach_notification",
            "dp_security_measures",
            "dp_subprocessing",
            "dp_retention_deletion",
            "dp_records_of_processing",
            "dp_localisation",
            "dp_dpia",
            "dp_dsr",
        ),
        rule_hints=(
            "data",
            "gdpr",
            "processor",
            "controller",
            "breach",
            "personal data",
            "processing",
        ),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="insurance",
        zone_name="Insurance Requirements",
        description="Insurance coverage, certificates, limits and waivers.",
        label_hints=(
            "insurance_requirements",
            "insurance_types_limits",
            "waiver_of_subrogation",
            "deductibles_limits",
            "business_continuity_bcp",
        ),
        rule_hints=(
            "insurance",
            "policy",
            "coverage",
            "certificate",
            "indemnity",
            "waiver",
        ),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="force_majeure",
        zone_name="Force Majeure",
        description="Force majeure events, mitigation, suspension rights and continuity planning.",
        label_hints=(
            "force_majeure",
            "business_continuity_bcp",
            "disaster_recovery",
            "backup_restore",
            "suspension",
            "step_in_rights",
        ),
        rule_hints=(
            "force majeure",
            "fm",
            "beyond control",
            "suspension",
            "continuity",
        ),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="taxes",
        zone_name="Taxes & Withholding",
        description="Indirect taxes, gross-up mechanics and anti-avoidance obligations.",
        label_hints=(
            "taxes_vat",
            "anti_tax_evasion",
            "price_changes_indexation",
            "set_off",
            "payment_terms",
        ),
        rule_hints=("tax", "vat", "withhold", "gross", "hmrc", "taxation"),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="assignment",
        zone_name="Assignment",
        description="Assignment restrictions, consent requirements and transfers.",
        label_hints=(
            "assignment",
            "joa_assignment_consent",
            "tenancy_assignment_underlet",
            "third_party_rights",
            "title_retention_rot",
        ),
        rule_hints=("assign", "transfer", "assignment", "consent", "delegate"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="subcontracting",
        zone_name="Subcontracting & Flow-down",
        description="Subcontract approvals, flow-down obligations and sub-processor controls.",
        label_hints=(
            "subcontracting",
            "subprocessor_approval",
            "dp_subprocessing",
            "support_maintenance",
            "staff_vetting",
        ),
        rule_hints=(
            "subcontract",
            "sub-contractor",
            "flow down",
            "subprocessor",
            "delegate",
        ),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="order_of_precedence",
        zone_name="Order of Precedence",
        description="Hierarchy between contract documents and precedence clauses.",
        label_hints=(
            "entire_agreement",
            "remedies",
            "third_party_rights",
            "waiver",
            "severance",
        ),
        rule_hints=("precedence", "order", "hierarchy", "conflict", "govern"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="definitions",
        zone_name="Definitions",
        description="Defined terms, parties and interpretation aids.",
        label_hints=(
            "definitions",
            "parties",
            "interpretation",
            "entire_agreement",
            "remedies",
        ),
        rule_hints=("definition", "defined", "capitalised", "interpretation", "means"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="interpretation",
        zone_name="Interpretation",
        description="Rules of construction, severability, waiver and entire agreement boilerplate.",
        label_hints=(
            "interpretation",
            "entire_agreement",
            "severance",
            "waiver",
            "remedies",
        ),
        rule_hints=("interpret", "construction", "including", "shall", "boilerplate"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="acceptance",
        zone_name="Acceptance & Testing",
        description="Acceptance testing, inspection rights and rejection procedures.",
        label_hints=(
            "acceptance_testing",
            "acceptance_it",
            "quality_control_qc",
            "warranty_conformity",
            "service_levels_sla",
        ),
        rule_hints=("acceptance", "test", "inspection", "criteria", "rejection"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="delivery",
        zone_name="Delivery & Performance",
        description="Delivery logistics, risk transfer and packaging obligations.",
        label_hints=(
            "delivery",
            "delivery_terms_incoterms",
            "risk_and_title",
            "packaging_labelling",
            "lead_times",
        ),
        rule_hints=("deliver", "delivery", "shipment", "incoterm", "risk", "title"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="service_levels",
        zone_name="Service Levels & Credits",
        description="Service level metrics, uptime, support and service credits.",
        label_hints=(
            "service_levels_sla",
            "service_credits",
            "saas_uptime",
            "support_maintenance",
            "quality_control_qc",
        ),
        rule_hints=(
            "service level",
            "sla",
            "uptime",
            "response",
            "service credit",
            "performance",
        ),
        entity_selectors={
            "amounts": True,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="price_adjustment",
        zone_name="Price Adjustments",
        description="Indexation, benchmarking, open book pricing and most favoured terms.",
        label_hints=(
            "price_changes_indexation",
            "open_book_pricing",
            "rate_card",
            "most_favoured_customer",
            "usage_limits",
        ),
        rule_hints=("price", "index", "benchmark", "open book", "mfn", "rate"),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="interest_late",
        zone_name="Late Payment Interest",
        description="Interest regimes, statutory remedies and payment enforcement.",
        label_hints=(
            "late_payment_interest",
            "payment_terms",
            "service_credits",
            "taxes_vat",
            "set_off",
        ),
        rule_hints=("late", "interest", "statutory", "late payment", "boe", "8%"),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
        required=True,
        high_importance=True,
    ),
    ZoneSeed(
        zone_id="change_control",
        zone_name="Change Control",
        description="Change request procedures, variation mechanics and approvals.",
        label_hints=(
            "change_control",
            "change_management_it",
            "variation",
            "construction_variations",
            "construction_programme",
        ),
        rule_hints=("change", "variation", "request", "cr", "change control"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="audit_records",
        zone_name="Audit & Records",
        description="Audit rights, record keeping and back-to-back compliance.",
        label_hints=(
            "audit_rights",
            "records_retention",
            "dp_audit",
            "dp_records_of_processing",
            "dp_back_to_back",
        ),
        rule_hints=("audit", "records", "inspection", "books", "access"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="survival",
        zone_name="Survival & Exit",
        description="Clauses surviving termination, exit assistance and post-termination obligations.",
        label_hints=(
            "survival",
            "termination_assistance",
            "records_retention",
            "return_or_destruction",
            "dp_retention_deletion",
        ),
        rule_hints=("survive", "survival", "post termination", "exit", "transition"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="personnel",
        zone_name="Personnel & Conduct",
        description="Key personnel, onboarding, vetting and conduct expectations.",
        label_hints=(
            "staff_vetting",
            "onboarding_migration",
            "equality_diversity",
            "conflicts_of_interest",
            "modern_slavery",
            "nhs_safeguarding",
        ),
        rule_hints=("personnel", "staff", "vet", "background", "conduct", "resources"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="cross_refs",
        zone_name="Cross References",
        description="References to other documents, transparency and publication duties.",
        label_hints=(
            "entire_agreement",
            "transparency_publication",
            "foi",
            "third_party_rights",
            "remedies",
        ),
        rule_hints=("reference", "schedule", "appendix", "publication", "transparency"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="warranties",
        zone_name="Warranties",
        description="Warranty scope, remedies, IP non-infringement and DOA/RMA processes.",
        label_hints=(
            "warranty_conformity",
            "warranty_performance",
            "warranty_ip_noninfringe",
            "warranty_doas_rma",
            "quality_control_qc",
            "remedies",
        ),
        rule_hints=("warranty", "warrant", "remedy", "defect", "non conform"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="quality",
        zone_name="Quality & Standards",
        description="Quality assurance, inspections, programme management and technical standards.",
        label_hints=(
            "quality_control_qc",
            "construction_defects_liability",
            "construction_programme",
            "construction_retention",
            "construction_eot",
            "construction_variations",
            "spares_obsolescence",
        ),
        rule_hints=("quality", "inspection", "programme", "retention", "defect"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="health_safety",
        zone_name="Health & Safety",
        description="Health and safety duties, hazardous materials controls and serious incident handling.",
        label_hints=(
            "health_and_safety",
            "hazardous_substances",
            "nhs_serious_incident",
            "nhs_safeguarding",
            "construction_health_safety_cdm",
        ),
        rule_hints=("health", "safety", "incident", "hazard", "cdm"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="compliance_abac",
        zone_name="Compliance & ABAC",
        description="Anti-bribery, tax evasion, modern slavery and ethical compliance.",
        label_hints=(
            "anti_bribery",
            "anti_tax_evasion",
            "modern_slavery",
            "equality_diversity",
            "sanctions_export_controls",
            "conflicts_of_interest",
        ),
        rule_hints=(
            "compliance",
            "anti",
            "bribery",
            "corruption",
            "modern slavery",
            "ethical",
        ),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="change_of_control",
        zone_name="Change of Control",
        description="Change of control triggers, operator provisions and joint operating agreement controls.",
        label_hints=(
            "termination_change_of_control",
            "joa_operator",
            "joa_opcom",
            "joa_marketing",
            "joa_default_nonconsent",
            "joa_work_program_budget",
        ),
        rule_hints=(
            "change of control",
            "coc",
            "operator",
            "joint operating",
            "default",
        ),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="background_ip",
        zone_name="Background IP",
        description="Pre-existing IP rights, tooling and retained ownership provisions.",
        label_hints=(
            "license_grant",
            "title_retention_rot",
            "tooling",
            "joa_work_program_budget",
            "joa_authorisation_for_expenditure",
        ),
        rule_hints=("background", "pre-existing", "tooling", "retained", "existing"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="foreground_ip",
        zone_name="Foreground IP",
        description="Developed IP ownership, indemnities and allocation in joint ventures.",
        label_hints=(
            "ip_ownership",
            "ip_indemnity",
            "joa_joint_accounting",
            "joa_marketing",
            "joa_operator",
        ),
        rule_hints=("foreground", "developed", "new ip", "joint", "work product"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="records_retention",
        zone_name="Records & Retention",
        description="Retention periods, localisation and destruction routines for records.",
        label_hints=(
            "records_retention",
            "dp_retention_deletion",
            "dp_records_of_processing",
            "return_or_destruction",
            "dp_localisation",
        ),
        rule_hints=("retention", "records", "destroy", "deletion", "archive"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="limitation_periods",
        zone_name="Limitation Periods",
        description="Limitation periods, carve outs and long-stop dates for claims.",
        label_hints=(
            "limitation_of_liability",
            "liability_cap_amount",
            "liability_carveouts",
            "liquidated_damages",
            "remedies",
        ),
        rule_hints=("limitation", "long stop", "claim", "time bar"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="setoff_withholding",
        zone_name="Set-off & Withholding",
        description="Rights to set-off, netting and withholding across accounts.",
        label_hints=(
            "set_off",
            "taxes_vat",
            "payment_terms",
            "payment_security",
            "anti_tax_evasion",
        ),
        rule_hints=("set-off", "setoff", "withhold", "net", "offset"),
        entity_selectors={
            "amounts": True,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="export_controls_sanctions",
        zone_name="Export Controls & Sanctions",
        description="Sanctions screening, export controls and trade compliance.",
        label_hints=(
            "sanctions_export_controls",
            "anti_bribery",
            "anti_tax_evasion",
            "modern_slavery",
            "foi",
        ),
        rule_hints=("sanction", "export", "trade", "embargo", "ofac"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="escrow_source_code",
        zone_name="Source Code Escrow",
        description="Escrow arrangements, release events and contingency tooling.",
        label_hints=(
            "escrow",
            "backup_restore",
            "disaster_recovery",
            "business_continuity_bcp",
            "tooling",
        ),
        rule_hints=("escrow", "source code", "release", "deposit", "escrow agent"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="step_in_rights",
        zone_name="Step-in Rights",
        description="Step-in triggers, remediation and continuity of services.",
        label_hints=(
            "step_in_rights",
            "nhs_step_in",
            "business_continuity_bcp",
            "support_maintenance",
            "disaster_recovery",
        ),
        rule_hints=("step in", "remedy", "continuity", "intervene", "direct control"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="novation",
        zone_name="Novation & Transfer",
        description="Novation mechanics, consents and successor obligations.",
        label_hints=(
            "assignment",
            "joa_assignment_consent",
            "tenancy_assignment_underlet",
            "third_party_rights",
            "termination_change_of_control",
        ),
        rule_hints=("novation", "transfer", "assign", "successor", "replacement"),
        entity_selectors={
            "amounts": False,
            "durations": False,
            "law": False,
            "jurisdiction": False,
        },
    ),
    ZoneSeed(
        zone_id="non_solicit_non_compete",
        zone_name="Non-solicit & Non-compete",
        description="Non-solicitation, restrictive covenants and safeguarding obligations.",
        label_hints=(
            "non_solicitation",
            "staff_vetting",
            "equality_diversity",
            "conflicts_of_interest",
            "nhs_safeguarding",
        ),
        rule_hints=("non solicit", "non-compete", "restraint", "poach", "restrictive"),
        entity_selectors={
            "amounts": False,
            "durations": True,
            "law": False,
            "jurisdiction": False,
        },
    ),
)


ZONE_LABEL_ALLOWLIST: Dict[str, FrozenSet[str]] = {}
ZONE_LABEL_BLACKLIST: Dict[str, FrozenSet[str]] = {}
ZONE_RULE_BLACKLIST: Dict[str, FrozenSet[str]] = {}

SERVICE_LABEL_IDS: FrozenSet[str] = frozenset()

HIGH_IMPORTANCE_ZONES: FrozenSet[str] = frozenset(
    seed.zone_id for seed in ZONE_SEED_DATA if seed.high_importance
)

ZONE_ENTITY_MATRIX: Dict[str, Dict[str, bool]] = {
    seed.zone_id: dict(seed.entity_selectors) for seed in ZONE_SEED_DATA
}
