name: ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install package (editable)
        run: pip install -e .
      - name: Pytest
        env:
          SKIP_LLM: "1"
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q --maxfail=1 --disable-warnings --cov=.
