name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Run pytest (fast fail)
        run: pytest -q --maxfail=1
      - name: Run quality metrics
        run: python -m contract_review_app.metrics.cli --out var/metrics/last.json
      - name: Compare with baseline
        run: python tools/metrics_compare.py --baseline metrics_baseline.json --current var/metrics/last.json
