name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  FEATURE_COMPANIES_HOUSE: "0"

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.11'
          - os: windows-latest
            python-version: '3.13'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest -q
  smoke-start:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Start API (uvicorn)
        shell: bash
        env:
          FEATURE_COMPANIES_HOUSE: "0"
          LLM_MODE: "mock"
          X_SCHEMA_VERSION: "1.4"
        run: |
          nohup python -m uvicorn contract_review_app.api.app:app \
            --host 127.0.0.1 --port 9443 --ssl-keyfile tests/certs/key.pem --ssl-certfile tests/certs/cert.pem > server.log 2>&1 &
          for i in {1..30}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" https://127.0.0.1:9443/health || true)
            [ "$code" = "200" ] && break
            sleep 1
          done
          curl -sk https://127.0.0.1:9443/health | sed -e 's/.*provider.*/[health scrubbed]/'
      - name: Run smoke tests
        run: pytest tests/test_routes_smoke.py::test_health_ok -q
