name: CI
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo CI placeholder
