name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.11'
          - os: windows-latest
            python-version: '3.13'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest -q
