name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FEATURE_COMPANIES_HOUSE: "0"
      API_KEY: local-test-key-123
      SCHEMA_VERSION: "1.4"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt || true
          python -m pip install pre-commit
          npm --prefix word_addin_dev ci
      - name: Diagnostics
        run: |
          python -V
          pip --version
          pip freeze | head -n 50
          pre-commit --version || python -m pre_commit --version || true
      - name: Pre-commit (check only)
        run: pre-commit run --all-files --show-diff-on-failure --color always
      - name: Prepare artifact dirs
        run: mkdir -p TRACE trace timings reports
      - name: Build add-in
        run: npm --prefix word_addin_dev run build
      - name: Build panel
        run: npm run build:panel
      - name: Run tests
        run: |
          mkdir -p reports
          pytest -q \
            tests/test_analyze_api.py tests/panel/test_panel_analyze_smoke.py \
            --junitxml=reports/pytest.xml || exit 1

      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/pytest.xml
          if-no-files-found: ignore

      - name: Upload TRACE artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trace-artifacts
          path: |

            TRACE
            trace
            timings
          if-no-files-found: ignore
