name: i18n-lint

on:
  push:
  pull_request:

env:
  FEATURE_COMPANIES_HOUSE: "0"

jobs:
  i18n-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.x'
      - name: Run python tools/i18n_scan.py
        run: python tools/i18n_scan.py || true
