name: i18n-lint

on:
  push:
  pull_request:

env:
  FEATURE_COMPANIES_HOUSE: "0"

jobs:
  i18n-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - run: python -m pip install -U pip
      - run: pip install -r requirements-dev.txt
      - name: Diagnostics
        run: |
          python -V
          pip --version
          pip freeze | head -n 50
          pre-commit --version || python -m pre_commit --version || true
      - name: Run python tools/i18n_scan.py
        run: python tools/i18n_scan.py || true
